leftnav:
- identifier: 98fc9098-d8c2-48f5-a7c7-e66ea5cfcf38
  name: mit
  pageRef: /external-resources/mit
  weight: 10
- identifier: 777ec395-ea35-4052-95f3-36ef32388d21
  name: google
  pageRef: /external-resources/google
  weight: 20
